package haxm.core;
public enum TagEnum{
	INVALID,
	SEND,
	REGISTER_DATACENTER,
	DATACENTERS_INFO_REQUEST,
	DATACENTERS_INFO_RESPONSE,
	DATACENTER_CONFIGURATION_REQUEST,
	DATACENTER_CONFIGURATION_RESPONSE
}
